### ISSUE TITLE
databricks_user.force flag is not working (most of the time :-/ )

### ISSUE THREAD

**Issue by gercograndia** [alexott/terraform-playground#1]
After running into limitations with the standard SCIM connector, and after consultation with both Microsoft and Databricks we were advised to use this project as a base for setting up our own sync pipeline. Which is what we did, and it was running fine, until we started getting errors like: `Error: cannot create user: User with email xxxxx already exists in this account`

The force​ flag should help here, but for whatever reason it stopped working. It is always difficult to find out exactly what did change but we're 100% that nothing changed in the versions of the terraform providers.

I tried to reproduce it in a very simple project, with two pre-existing users, and in the end one succeeds while the other keeps on failing:

```hcl
#
# Creation of this user succeeds, force flag is doing its thing
#
resource "databricks_user" "marco" {
    user_name    = "xxxxxxx"
    display_name = "XXXXXX"
    active       = true
    disable_as_user_deletion = false
    external_id  = "xxx-xxx-xxx"

    force = true
}

#
# This one fails with:  Error: cannot create user: User with email yyyyyy already exists in this account
#
resource "databricks_user" "dimitry" {
    user_name    = "yyyyyy"
    display_name = "YYYYYY"
    active       = true
    disable_as_user_deletion = false
    external_id  = "yyy-yyy-yyy"

    force = true
}
```

To add to the intrigue, the one that is failing initially succeeded too but after toggling the disable_as_user_deletion​ flag it all of a sudden started to fail. And kept on failing, whatever I tried. So it seems there is something in the user config that differs between the two?

I know the `force` flag is experimental, although I think it has to be officially supported one way or the other, as I can never prevent users from being created automatically. Hence there must be a way to support this.

Could very well be that this is not the project to ask a question like this, but perhaps you ran into it and know how to deal with this?

**Comment by alexott** [comment]
Please open an issue in https://github.com/databricks/terraform-provider-databricks/issues with all logs, etc. as it is most probably a bug in the provider.

**Comment by gercograndia** [comment]
Just did, thanks 👍

**Comment by gercograndia** [comment]
https://github.com/databricks/terraform-provider-databricks/issues/3085
